name: Resolve Issue with OpenHands

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  call-openhands-resolver:
    uses: OpenHands/OpenHands/.github/workflows/openhands-resolver.yml@main
    with:
      macro: ${{ vars.OPENHANDS_MACRO || '@openhands-agent' }}
      max_iterations: ${{ fromJson(vars.OPENHANDS_MAX_ITER || 50) }}
      # base_container_image: ${{ vars.OPENHANDS_BASE_CONTAINER_IMAGE || '' }}
      LLM_MODEL: ${{ vars.LLM_MODEL || 'openrouter/openai/gpt-4o-mini' }}
      target_branch: ${{ vars.TARGET_BRANCH || 'main' }}
      runner: ${{ vars.TARGET_RUNNER }}
      auto_merge: true
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      # LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
#      Attribute name	Type	Purpose	Example
#LLM_MODEL	Variable	Set the LLM to use with OpenHands	LLM_MODEL="anthropic/claude-3-5-sonnet-20241022"
#OPENHANDS_MAX_ITER	Variable	Set max limit for agent iterations	OPENHANDS_MAX_ITER=10
#OPENHANDS_MACRO	Variable	Customize default macro for invoking the resolver	OPENHANDS_MACRO=@resolveit
#OPENHANDS_BASE_CONTAINER_IMAGE	Variable	Custom Sandbox (learn more)	OPENHANDS_BASE_CONTAINER_IMAGE="custom_image"
#TARGET_BRANCH	Variable	Merge to branch other than main	TARGET_BRANCH="dev"
#TARGET_RUNNER	Variable	Target runner to execute the agent workflow (default ubuntu-latest)	TARGET_RUNNER="custom-runner"
